<!--
% \VignetteIndexEntry{Using repositories other than CRAN with miniCRAN}
% \VignetteEngine{knitr::knitr}
% \VignettePackage{miniCRAN}
% \VignetteKeyword{miniCRAN}
--> 

# Using repositories other than CRAN with miniCRAN



```{r setup}
# Wrapper around available.packages ---------------------------------------
 
index <- function(url, type="source", filters=NULL, head=5, cols=c("Package", "Version")){
  contribUrl <- contrib.url(url, type=type)
  p <- available.packages(contribUrl, type=type, filters=filters)
  p[1:head, cols]
}
 
```

## Using CRAN

```{r CRAN}
CRAN <- "http://cran.r-project.org"
index(CRAN)
```


## Using a different mirror

```{r revo}
revoStable <- "http://packages.revolutionanalytics.com/cran/3.1/stable"
index(revoStable)
 
revoMirror <- "http://cran.revolutionanalytics.com"
index(revoMirror)
```

## Using R-forge

```{r rforge}
rforge <- "http://r-forge.r-project.org"
index(rforge)
```

## Using BioConductor

```{r bioc}
bioc <- local({
  on.exit(rm(env))
  env <- new.env()
  evalq(source("http://bioconductor.org/biocLite.R", local=TRUE), env)
  biocinstallRepos()
})
 
bioc
bioc[grep("BioC", names(bioc))]
 
 
index(bioc["BioCsoft"])
```